server:
  port: 8081

spring:
  datasource.primary:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/networking?useUnicode=true&useSSL=false&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: qbq123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    filters: stat,wall,log4j
  datasource.second:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/networking?useUnicode=true&useSSL=false&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: qbq123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    filters: stat,wall,log4j
  rabbitmq:
    host: www.haeport.com
    virtualHost: ase
    port: 5672
    username: username
    password: password
    
logging:
   config: classpath:logback-spring.xml
  
    